# Generated by Django 5.2.5 on 2025-08-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
